import { type EventSubscription, requireNativeModule } from 'expo-modules-core';

export {
  attachment_open_chunk_export,
  attachment_prepare_export,
  attachment_seal_chunk_export,
  journal_load_export,
  journal_save_export,
  backup_begin_export,
  backup_confirm_export,
  backup_status_export,
  backup_prepare_export,
  backup_part_export,
  backup_finish_export,
  backup_disable_export,
  backup_restore_slots_export,
  backup_restore_begin_export,
  backup_restore_chunk_export,
  backup_restore_finish_export,
  backup_restore_identity_export,
  backup_restore_account_export,
  presentation_load_export,
  presentation_save_export,
  create_account_export,
  create_link_request_export,
  device_link_sas_export,
  directory_entry_export,
  directory_lookup_export,
  group_add_export,
  group_create_export,
  group_history_export,
  group_inspect_export,
  group_key_package_export,
  group_invite_export,
  group_invitation_accept_export,
  group_invitation_complete_export,
  group_invitation_decline_export,
  group_invitations_export,
  group_forget_export,
  group_list_export,
  group_receive_export,
  group_remove_export,
  group_send_export,
  import_contact_export,
  initialize,
  authorize_device_link_for_set_export,
  complete_device_link_export,
  create_device_revocation_export,
  account_deletion_export,
  erase_account_export,
  device_departure_export,
  forget_on_proof_export,
  inspect_device_set_export,
  list_conversations_export,
  load_history_export,
  load_profile_export,
  mailbox_fetch_export,
  outbox_ack_export,
  outbox_fail_export,
  outbox_page_export,
  outbox_list_export,
  persist_envelope,
  process_delivery_batch_export,
  privacy_submission_export,
  push_action_complete_export,
  push_intent_export,
  push_status_export,
  replenish_prekeys_export,
  reconcile_prekeys_export,
  receive_initial_export,
  receive_message_export,
  prepare_fanout_prekeys_export,
  send_fanout_export,
  safety_number_export,
  transparency_lookup_export,
  register_request_export,
  renew_devices_export,
  resolve_request_export,
  oblivious_encapsulate_export,
  oblivious_decapsulate_export,
  update_conversation_export,
  validate_outer,
  verify_transparency_export,
  transparency_anchor_requests_export,
  transparency_anchor_proof_export,
  network_status_export,
  wallet_rpc_urls_export,
  anchor_check_export,
  gossip_check_export,
  trust_alarm_details_export,
  expiry_purge_export,
  group_timer_export,
  group_timer_state_export,
  send_view_once_export,
  group_send_view_once_export,
  open_view_once_export,
  group_open_view_once_export,
  safety_code_export,
  safety_code_check_export,
  credits_status_export,
  credits_refresh_keys_export,
  credits_quote_export,
  credits_issue_export,
  credits_postage_export,
  credits_postage_quote_export,
  credits_retention_export,
  credits_signup_export,
  credits_register_at_export,
  credits_spend_export,
  credits_settle_export,
  credits_inbox_policy_export,
  credits_group_handover_export,
} from './generated/libmessenger_mobile';

type PushNativeModule = {
  primePushToken(): Promise<void>;
  clearPushToken(): Promise<void>;
  addListener(
    event: 'onPushRegistrationChanged',
    listener: () => void,
  ): EventSubscription;
};

const pushNative = requireNativeModule<PushNativeModule>('MeshMessenger');

export const primePushToken = (): Promise<void> => pushNative.primePushToken();
export const clearPushToken = (): Promise<void> => pushNative.clearPushToken();

export function onPushRegistrationChanged(listener: () => void): () => void {
  const subscription = pushNative.addListener('onPushRegistrationChanged', listener);
  return () => subscription.remove();
}
