// Desktop uses the same exported ABI as the generated mobile bindings.
import { invokeMesh } from "../../src/desktop";
const native = { invoke: invokeMesh };

export const initialize = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_initialize', request);
export const validate_outer = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_validate_outer', request);
export const persist_envelope = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_store_envelope', request);
export const create_account_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_create_account', request);
export const load_profile_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_load_profile', request);
export const replenish_prekeys_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_replenish_prekeys', request);
export const reconcile_prekeys_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_reconcile_prekeys', request);
export const create_link_request_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_create_link_request', request);
export const device_link_sas_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_device_link_sas', request);
export const authorize_device_link_for_set_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_authorize_device_link_for_set', request);
export const complete_device_link_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_complete_device_link', request);
export const inspect_device_set_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_inspect_device_set', request);
export const create_device_revocation_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_create_device_revocation', request);
export const account_deletion_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_account_deletion', request);
export const erase_account_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_erase_account', request);
export const device_departure_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_device_departure', request);
export const forget_on_proof_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_forget_on_proof', request);
export const receive_initial_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_receive_initial', request);
export const prepare_fanout_prekeys_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_prepare_fanout_prekeys', request);
export const send_fanout_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_send_fanout', request);
export const group_key_package_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_key_package', request);
export const group_invite_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_invite', request);
export const group_invitation_accept_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_invitation_accept', request);
export const group_invitation_complete_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_invitation_complete', request);
export const group_invitation_decline_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_invitation_decline', request);
export const group_invitations_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_invitations', request);
export const group_create_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_create', request);
export const group_add_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_add', request);
export const group_remove_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_remove', request);
export const group_send_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_send', request);
export const group_receive_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_receive', request);
export const group_list_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_list', request);
export const group_inspect_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_inspect', request);
export const group_history_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_group_history', request);
export const receive_message_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_receive_message', request);
export const update_conversation_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_update_conversation', request);
export const push_intent_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_push_intent', request);
export const push_action_complete_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_push_action_complete', request);
export const push_status_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_push_status', request);
export const list_conversations_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_list_conversations', request);
export const load_history_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_load_history', request);
export const safety_number_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_safety_number', request);
export const import_contact_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_import_contact', request);
export const directory_entry_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_directory_entry', request);
export const directory_lookup_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_directory_lookup', request);
export const transparency_lookup_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_transparency_lookup', request);
export const register_request_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_register_request', request);
export const resolve_request_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_resolve_request', request);
export const verify_transparency_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_verify_transparency', request);
export const privacy_submission_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_privacy_submission', request);
export const mailbox_fetch_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_mailbox_fetch', request);
export const process_delivery_batch_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_process_delivery_batch', request);
export const outbox_list_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_outbox_list', request);
export const outbox_ack_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_outbox_ack', request);
export const outbox_fail_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_outbox_fail', request);
export const outbox_page_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_outbox_page', request);

export const primePushToken = async (): Promise<void> => { throw new Error("Desktop uses live updates while open"); };
export const clearPushToken = async (): Promise<void> => {};
export const onPushRegistrationChanged = (_listener: () => void): (() => void) => () => {};

export const journal_load_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_journal_load', request);
export const journal_save_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_journal_save', request);
export const presentation_load_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_presentation_load', request);
export const presentation_save_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_presentation_save', request);
export const attachment_prepare_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_attachment_prepare', request);
export const attachment_seal_chunk_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_attachment_seal_chunk', request);
export const attachment_open_chunk_export = (request: Uint8Array): Promise<Uint8Array> => native.invoke('mesh_messenger_attachment_open_chunk', request);
