// Renders every app-icon asset from the Morse mark in src/brand.ts.
//
//   npm run render-icons
//
// Mobile assets land in assets/ (referenced by app.config.js); the desktop
// source lands next to the Tauri icons so `npx tauri icon` can fan it out.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";
import { gray } from "../src/tokens.ts";

import {
  ANDROID_SAFE_SCALE,
  MARK_CANVAS,
  MARK_GRADIENT,
  MARK_PATH,
  markTransform,
} from "../src/brand.ts";

const mobileRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const assetsDir = join(mobileRoot, "assets");
const desktopIconsDir = resolve(mobileRoot, "../desktop/src-tauri/icons");

const S = MARK_CANVAS;
const canvasColors = { from: "#1E1E25", to: "#0A0A0C" };

function gradient(id, { from, to }) {
  return `<linearGradient id="${id}" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="${from}"/><stop offset="1" stop-color="${to}"/>
  </linearGradient>`;
}

const sheen = `<linearGradient id="sheen" x1="0" y1="0" x2="0" y2="1">
  <stop offset="0" stop-color="#FFFFFF" stop-opacity="0.22"/>
  <stop offset="0.5" stop-color="#FFFFFF" stop-opacity="0"/>
</linearGradient>`;

function mark(fill, transform = markTransform(1)) {
  return `<path fill="${fill}" transform="${transform}" d="${MARK_PATH}"/>`;
}

function document(body, defs = "") {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${S} ${S}"><defs>${defs}</defs>${body}</svg>`;
}

const accentField = `<rect width="${S}" height="${S}" fill="url(#field)"/><rect width="${S}" height="${S}" fill="url(#sheen)"/>`;

export const variants = {
  "splash.png": document(mark("url(#accent)"), gradient("accent", MARK_GRADIENT)),
  // iOS light icon and the generic fallback: full-bleed accent field, white mark.
  "icon.png": document(`${accentField}${mark("#FFFFFF")}`, gradient("field", MARK_GRADIENT) + sheen),
  // iOS dark appearance keeps the brand colour in the foreground.
  "icon-dark.png": document(
    `<rect width="${S}" height="${S}" fill="url(#canvas)"/>${mark("url(#accent)")}`,
    gradient("canvas", canvasColors) + gradient("accent", MARK_GRADIENT),
  ),
  // iOS tinted appearance reads luminance from an opaque grayscale image: black
  // becomes the system backdrop, white takes the full tint. (Expo flattens any
  // transparency here onto white, which would erase a white mark.)
  "icon-tinted.png": document(`<rect width="${S}" height="${S}" fill="#000000"/>${mark("#FFFFFF")}`),
  // Android adaptive layers: the mark shrinks into the safe zone, the field is a separate layer.
  "adaptive-icon.png": document(mark("#FFFFFF", markTransform(ANDROID_SAFE_SCALE))),
  "adaptive-icon-background.png": document(accentField, gradient("field", MARK_GRADIENT) + sheen),
};

// macOS expects the rounded square drawn inside the canvas with a soft shadow;
// Windows and Linux are happy with the same transparent-margin image.
const desktopInset = 100;
const desktopSize = S - desktopInset * 2;
const desktopRadius = desktopSize * 0.2237;
export const desktopSource = document(
  `<rect x="${desktopInset}" y="${desktopInset + 14}" width="${desktopSize}" height="${desktopSize}" rx="${desktopRadius}" fill="#000" opacity="0.32" filter="url(#shadow)"/>
   <clipPath id="tile"><rect x="${desktopInset}" y="${desktopInset}" width="${desktopSize}" height="${desktopSize}" rx="${desktopRadius}"/></clipPath>
   <g clip-path="url(#tile)">${accentField}${mark("#FFFFFF", markTransform(desktopSize / S))}</g>`,
  gradient("field", MARK_GRADIENT) +
    sheen +
    `<filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="18"/></filter>`,
);

function render(svg, file, width = S) {
  const png = new Resvg(svg, { fitTo: { mode: "width", value: width } }).render().asPng();
  writeFileSync(file, png);
  console.log(`wrote ${file} (${width}px, ${png.length} bytes)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  mkdirSync(assetsDir, { recursive: true });
  mkdirSync(desktopIconsDir, { recursive: true });
  for (const [file, svg] of Object.entries(variants)) render(svg, join(assetsDir, file));
  writeFileSync(join(assetsDir, "morse-mark.svg"), document(mark("#FFFFFF")));
  render(desktopSource, join(desktopIconsDir, "icon-source.png"));
  // Expo serves this before any bundle or font loads. It shares the native
  // splash's geometry and canvas; React removes it only after laying out.
  const publicDir = join(mobileRoot, "public");
  mkdirSync(publicDir, { recursive: true });
  writeFileSync(join(publicDir, "index.html"), `<!DOCTYPE html>
<!-- Generated by npm run render-icons. -->
<html lang="%LANG_ISO_CODE%">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>%WEB_TITLE%</title>
    <style>
      html, body, #root { height: 100%; margin: 0; background: ${gray[1000]}; }
      body { overflow: hidden; }
      #root { display: flex; flex: 1; }
      #morse-launch { position: fixed; inset: 0; z-index: 1000; display: flex; align-items: center; justify-content: center; background: ${gray[1000]}; }
      #morse-launch svg { width: 200px; height: 200px; }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <div id="morse-launch" role="progressbar" aria-label="Opening Morse" aria-busy="true">
      ${variants["splash.png"].replace('<svg ', '<svg aria-hidden="true" ')}
    </div>
  </body>
</html>
`);
}
