[package]
name = "meshc"
version = "0.1.0"
edition = "2021"
description = "The Mesh compiler"

[dependencies]
mesh-common = { path = "../mesh-common" }
mesh-lexer = { path = "../mesh-lexer" }
mesh-parser = { path = "../mesh-parser" }
mesh-typeck = { path = "../mesh-typeck" }
mesh-codegen = { path = "../mesh-codegen" }
mesh-lsp = { path = "../mesh-lsp" }
mesh-fmt = { path = "../mesh-fmt" }
mesh-pkg = { path = "../mesh-pkg" }
mesh-repl = { path = "../mesh-repl" }
mesh-rt = { path = "../mesh-rt" }
clap = { workspace = true }
tempfile = "3"
ariadne = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
base64 = "0.22"
tokio = { workspace = true }

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = { workspace = true }
openssl-sys = { version = "0.9", features = ["vendored"] }

[dev-dependencies]
tempfile = "3"
serde = { workspace = true }
serde_json = { workspace = true }
