[package]
name = "mesh-messenger-cli"
version = "0.1.0"

[dependencies]
mesh-binary = { path = "../../../mesh-lang/packages/mesh-binary" }
messenger-protocol = { path = "../../packages/messenger-protocol" }
